[project]
name = "sesh-importer"

[bin]
main = "src/Main.saga"

# [library]
# module = "SeshImporter"
# expose = []

[deps]
saga_csv = { git = "../../saga_csv" }
saga_pgo = { path = "../../saga_pgo" }
saga_json = { path = "../../saga_json" }
kraken = { path = "../../kraken" }
